#-------------------------------------------------------------------------------
# Load packages:  R3.3.3  or plus
#-------------------------------------------------------------------------------
#!!! packman enables to load at once
'install.packages("pacman")
pacman::p_load(highcharter, olsrr) '


Sys.setlocale(category = "LC_TIME", locale="")                                   # base should not be in french!!!!
Sys.setlocale("LC_TIME", "C")

graphics.off()

library(subprocess)
library(jsonlite)
library(gWidgets2tcltk)
library(gWidgets2)
library(reshape2)
library(xlsx)
library(dplyr)
library(XLConnect)
library(base)
library(seasonal)
library(zoo)
library(timeDate)
library(forecast)
library(data.table)
library(tseries)
library(fma)
library(expsmooth)
library(lmtest)
library(fpp)
library(reshape)
library(shiny)
library(devtools)
library(ggplot2)
library(labeling)
library(tsoutliers)
library(DBI)
library(RSQLite)
library(proto)
library(gsubfn)
library(sqldf)
library(pracma)
library(maptools)
library(gridExtra)
library(maps)
library(mapdata)
library(ggmap)
library(plyr)
library(TTR)
require(XLConnect)
library(corrplot)
library(digest)
library(ggthemes)
library(lubridate) #ymd
library(stargazer)                                                               
library(maps)       
library(mapdata)    
library(scales)
library(texreg)
library(datasets)
library(ade4)
library(htmltools)
library(chron)
library(lubridate) 
library(tidyr)
library(tableHTML)
library(RSQLite)
library(data.table)                           										
library(dplyr)
library(ggplot2)
library(reshape2)
library(effects)
library(rlist)
library(broom)
library(forecast)
library(wesanderson)
library(imputeTS)
library(dygraphs)
library(zoo)
library(highcharter)
library(xts)
library(MASS)
library(leaps)
# library(olsrr)
library(stats)
library(strucchange)
library(imputeTS)


graphics.off()